# Generated by Django 4.2.7 on 2024-08-06 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='master.employee')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
