# Generated by Django 4.2.7 on 2024-08-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empolyee_no',
            new_name='employee_no',
        ),
    ]
